# Generated by Django 3.2.15 on 2024-12-11 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskInfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='', max_length=64, verbose_name='key')),
                ('status', models.IntegerField(choices=[(0, 'progressing'), (1, 'completed'), (2, 'error')], default=0, verbose_name='status')),
            ],
            options={
                'verbose_name': 'task_info',
                'verbose_name_plural': 'task_info',
                'db_table': 'task_info',
            },
        ),
    ]
