# Generated by Django 3.2.15 on 2024-12-11 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskinfomodel',
            name='status',
            field=models.IntegerField(choices=[(0, 'completed'), (1, 'progressing'), (2, 'error')], default=0, verbose_name='status'),
        ),
    ]
