# Generated by Django 3.2.15 on 2024-12-11 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_taskinfomodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskinfomodel',
            name='key',
            field=models.CharField(default=1, max_length=64, verbose_name='key'),
        ),
    ]
