# Generated by Django 3.2.15 on 2024-12-12 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_taskinfomodel_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskinfomodel',
            name='id',
        ),
        migrations.AlterField(
            model_name='taskinfomodel',
            name='key',
            field=models.CharField(default='', max_length=64, primary_key=True, serialize=False, verbose_name='key'),
        ),
    ]
