[program:celery]
command=sudo su root
command=/data3/platform/marine/envs/dsm/celery -A server celery_worker.celery --loglevel=info
directory=/home/platform/project/dsm_platform/dsm-server/dsm-server/server
user='root'
autostart=true
autorestart=true
stderr_logfile=/home/platform/project/dsm_platform/dsm-server/log/celery.err.log
stdout_logfile=/home/platform/project/dsm_platform/dsm-server/log/celery.out.log
